# Starter pipeline
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'maven build'
    targetPath: '$(Pipeline.Workspace)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
   
- script: echo Hello, world!
  displayName: 'Run a one-linescript'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ContainerStructureTest@0
  inputs:
    configFile: '/'
    testRunTitle: 'test'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '/'